### ISSUE TITLE
Add translation support via tw.n

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExternalQueryLookup#2]
@mwjames In case there are no more system messages in the pipeline @JeroenDeDauw could ask for the required wmf repo

**Comment by mwjames** [comment]
> @mwjames In case there are no more system messages in the pipeline

More system messages are not scheduled to appear.

**Comment by kghbln** [comment]
Mirror repo [requested](https://www.mediawiki.org/w/index.php?title=Git%2FNew_repositories%2FRequests%2FEntries&action=historysubmit&type=revision&diff=1941908&oldid=1941300)

**Comment by kghbln** [comment]
@JeroenDeDauw [You'r up](https://www.mediawiki.org/w/index.php?title=Git/New_repositories/Requests/Entries&diff=1944109&oldid=1941920) :)

**Comment by JeroenDeDauw** [comment]
Synced

**Comment by kghbln** [comment]
Thanks. [Phab task](https://phabricator.wikimedia.org/T119350) created. Sit tight!

**Comment by kghbln** [comment]
It has all happened.
