### ISSUE TITLE
Composer require error: "conflict with your requirements or minimum-stability" 

### ISSUE THREAD

**Issue by datawiki** [SemanticMediaWiki/SemanticExternalQueryLookup#34]
### composer require mediawiki/semantic-external-query-lookup:~1.0

- SMW version: 3.2.2
- MW version: 1.35.1
- DB (MySQL etc.): Maria 10.3.2
- PHP version: 7.4.14 

### Issue 
```
  Problem 1
    - The requested package mediawiki/semantic-external-query-lookup ~1.0 is satisfiable by mediawiki/semantic-external-query-lookup[1.x-dev] but these conflict with your requirements or minimum-stability.
```
Brand new clean install.

**Comment by datawiki** [comment]
Solution is to add following to composer.json.   Found it [here](https://stackoverflow.com/questions/45019784/but-these-conflict-with-your-requirements-or-minimum-stability).

```json
{
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by kghbln** [comment]
Thanks for sharing your troubles and your solution to it. Also have a look at SMW native option [to query foreign instances](https://sandbox.semantic-mediawiki.org/wiki/My_second_external_query)
